apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ClusterManagementAddOn
metadata:
  name: ocm-addon-boilerplate
spec:
  addOnMeta:
    displayName: OCM Addon Boilerplate
    description: "OCM addon boilerplate demonstrating multiple spoke-hub communication strategies"
  installStrategy:
    type: Placements
    placements:
      - name: all-managed-clusters
        namespace: open-cluster-management
