apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocm-addon-boilerplate-controller
  namespace: open-cluster-management
  labels:
    app: ocm-addon-boilerplate-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocm-addon-boilerplate-controller
  template:
    metadata:
      labels:
        app: ocm-addon-boilerplate-controller
    spec:
      serviceAccountName: ocm-addon-boilerplate-sa
      containers:
        - name: controller
          image: ocm-addon-boilerplate:latest
          imagePullPolicy: IfNotPresent
          args:
            - "controller"
          env:
            - name: ADDON_IMAGE
              value: "ocm-addon-boilerplate:latest"
